name: C/C++ CI

on:
  push:
    branches: [ "master", "next" ]
  pull_request:
    branches: [ "master", "next" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable GCC (GCC 14)
        uses: egor-tensin/setup-g++@v3
        with:
          version: 15  # Pin to the current latest stable version
          platform: x64
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: cmake
        run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
      - name: ninja
        run: ninja
      - name: ninja test
        run: ninja test


  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: cmake
      run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="/EHsc" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    - name: ninja
      run: ninja
    - name: ninja test
      run: ninja test

  windows-debug:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: cmake
      run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDebugDLL" -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="/fsanitize=address /EHsc" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
    - name: ninja
      run: ninja
    - name: ninja test
      run: ninja test

  #macos:

  #  runs-on: macos-latest

  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Install ninja-build tool
  #    uses: seanmiddleditch/gha-setup-ninja@v4
  #  - name: cmake
  #    run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
  #  - name: ninja
  #    run: ninja
  #  - name: ninja test
  #    run: ninja test

